{===============================================================================
  Markup™ - Document Authoring Language

  Copyright © 2026-present tinyBigGAMES™ LLC
  All Rights Reserved.

  See LICENSE for license information
===============================================================================}

unit UTest.Demo.API;

{$I Markup.Defines.inc}

interface

procedure Demo_API_ConvertToFile();
procedure Demo_API_ParseRenderMany();
procedure Demo_API_Validate();
procedure Demo_API_LastErrors();
procedure Demo_API_IncludePaths();

implementation

uses
  System.SysUtils,
  System.IOUtils,
  Markup.Utils,
  Markup,
  UTest.Demo;

// =========================================================================
// ConvertToFile — one-shot convert, save to HTML, open in browser
// =========================================================================
procedure Demo_API_ConvertToFile();
var
  LEngine: TMuEngine;
begin
  DemoHeader('API: ConvertToFile');
  LEngine := markup_create();
  try
    DemoSetHandlers(LEngine);
    DemoResult(markup_convert_to_file(LEngine,
      Mu('{h1 "ConvertToFile Demo"}' +
         '{p "This HTML was generated by {code "markup_convert_to_file"} ' +
         'and saved directly to disk."}' +
         '{h2 "User: {=data.name}"}' +
         '{p "Role: {=data.role}"}' +
         '{note "This file was auto-opened in your default browser."}'),
      Mu('{"name":"Alice Chen","role":"Lead Engineer"}'),
      OutputFile('API_ConvertToFile'), OpenInBrowser));
  finally
    markup_destroy(LEngine);
  end;
end;

// =========================================================================
// ParseRenderMany — parse once, render with different data sets
// =========================================================================
procedure Demo_API_ParseRenderMany();
var
  LEngine: TMuEngine;
  LDoc: TMuDoc;
  LHtml: PAnsiChar;
begin
  DemoHeader('API: Parse Once, Render Many');
  LEngine := markup_create();
  try
    DemoSetHandlers(LEngine);
    LDoc := markup_parse(LEngine,
      Mu('{box class=email' +
         '  {p "Dear {=data.name},"}' +
         '  {if {=data.isRenewal}' +
         '    {p "Thank you for renewing your {=data.plan} subscription!"}' +
         '  {else}' +
         '    {p "Welcome to our {=data.plan} plan!"}' +
         '  }' +
         '  {p "Best regards,{br}The Team"}' +
         '}'));
    try
      TMuUtils.PrintLn(COLOR_YELLOW + '  [Renewal user]' + COLOR_RESET);
      LHtml := markup_render(LEngine, LDoc,
        Mu('{"name":"Bob","isRenewal":true,"plan":"Pro"}'));
      try
        TMuUtils.PrintLn(MuStr(LHtml));
      finally
        markup_free(LHtml);
      end;

      TMuUtils.PrintLn(COLOR_YELLOW + '  [New user]' + COLOR_RESET);
      LHtml := markup_render(LEngine, LDoc,
        Mu('{"name":"Carol","isRenewal":false,"plan":"Starter"}'));
      try
        TMuUtils.PrintLn(MuStr(LHtml));
      finally
        markup_free(LHtml);
      end;
    finally
      markup_doc_destroy(LDoc);
    end;
  finally
    markup_destroy(LEngine);
  end;
  TMuUtils.PrintLn('');
end;

// =========================================================================
// Validate — check source for errors without rendering
// =========================================================================
procedure Demo_API_Validate();
var
  LEngine: TMuEngine;
  LErrors: PAnsiChar;
begin
  DemoHeader('API: Validate');
  LEngine := markup_create();
  try
    DemoSetHandlers(LEngine);

    TMuUtils.PrintLn(COLOR_YELLOW + '  [Valid source]' + COLOR_RESET);
    LErrors := markup_validate(LEngine,
      Mu('{h1 "Hello"}{p "World."}'));
    try
      TMuUtils.PrintLn('  Diagnostics: ' + MuStr(LErrors));
    finally
      markup_free(LErrors);
    end;

    TMuUtils.PrintLn(COLOR_YELLOW +
      '  [Broken source]' + COLOR_RESET);
    LErrors := markup_validate(LEngine,
      Mu('{include "nonexistent_file.mu"}'));
    try
      TMuUtils.PrintLn('  Diagnostics: ' + MuStr(LErrors));
    finally
      markup_free(LErrors);
    end;
  finally
    markup_destroy(LEngine);
  end;
  TMuUtils.PrintLn('');
end;

// =========================================================================
// LastErrors — retrieve error list after a failed convert
// =========================================================================
procedure Demo_API_LastErrors();
var
  LEngine: TMuEngine;
  LHtml: PAnsiChar;
  LErrors: PAnsiChar;
begin
  DemoHeader('API: LastErrors');
  LEngine := markup_create();
  try
    DemoSetHandlers(LEngine);

    LHtml := markup_convert(LEngine, Mu(''), nil);
    try
      TMuUtils.PrintLn('  Output: "' + MuStr(LHtml) + '"');
    finally
      markup_free(LHtml);
    end;

    LErrors := markup_last_errors(LEngine);
    try
      TMuUtils.PrintLn('  Last errors: ' + MuStr(LErrors));
    finally
      markup_free(LErrors);
    end;
  finally
    markup_destroy(LEngine);
  end;
  TMuUtils.PrintLn('');
end;

// =========================================================================
// IncludePaths — add search paths for {include} resolution
// =========================================================================
procedure Demo_API_IncludePaths();
var
  LEngine: TMuEngine;
  LPartialsDir: string;
begin
  DemoHeader('API: Include Paths');

  LPartialsDir := OutputPath + '\partials';
  TMuUtils.CreateDirInPath(LPartialsDir + '\dummy');
  TFile.WriteAllText(LPartialsDir + '\header.mu',
    '{header {h1 "Site Header"}{nav {p "Home | About | Contact"}}}',
    TEncoding.UTF8);

  LEngine := markup_create();
  try
    DemoSetHandlers(LEngine);
    markup_add_include_path(LEngine, Mu(LPartialsDir));

    DemoResult(markup_convert_to_file(LEngine,
      Mu('{include "header.mu"}' +
         '{main' +
         '  {h2 "Page Content"}' +
         '  {p "This page includes a shared header partial."}' +
         '}'),
      nil, OutputFile('API_IncludePaths'), OpenInBrowser));
  finally
    markup_destroy(LEngine);
  end;
end;

end.
